### ISSUE TITLE
Project is lacking a README file.

### ISSUE THREAD

**Issue by VaishU2235** [prabinrajkp/covidWebapp#2]
This project is intended to be a "learning by doing" experience for the developer team. But to be more developer-friendly, we need a README file that showcases the basic usage of our app and the features of the DASH app. It should include the following details:

1.  Clicking on a bar in the bar chart makes changes in the adjacent pie chart. (APP Feature)
2.  Clicking on a legend item of the pie chart makes that item disappear (You can use this feature to sell total vs partially vaccinated). (DASH Feature)
3. In the state comparison tab, selecting no state will result in the line chart of India. (APP Feature)
4. In the state comparison tab, the Search option is available. (DASH Feature)

**Comment by Adheena19** [comment]
Readme is completed. Please check and comment .

**Comment by VaishU2235** [comment]
Re-Opening the issue for two reasons.
First, try to close the issue only after the pull request is merged.
Second, as we have decided to limit the responsiveness of the chart the content related to zoom-in/out can be removed. For more comments, check #5.
